### ISSUE TITLE
[Crash] ArrayIndexOutOfBoundsException: Clicking "<" after launch of app

### ISSUE THREAD

**Issue by sorianog** [DeepARSDK/photoedit-android-java#3]
The trace: 
`
2020-03-07 19:35:06.155 29123-29123/ai.deepar.photo_edit_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.deepar.photo_edit_example, PID: 29123
    java.lang.ArrayIndexOutOfBoundsException: length=22; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at ai.deepar.photo_edit_example.MainActivity.gotoPrevious(MainActivity.java:278)
        at ai.deepar.photo_edit_example.MainActivity.access$200(MainActivity.java:52)
        at ai.deepar.photo_edit_example.MainActivity$6.onClick(MainActivity.java:210)
`

It seems like a trivial fix but something I was quickly able to come across during exploratory testing!

**Comment by JelenaKB** [comment]
Thank you for bringing this to our attention, it has been fixed.
